#!/usr/bin/env python3
"""
sprite2asm.py - turn sprite art into tft4 4 bpp sprite data (TI assembler).

Input: a text file of sprites, or PNG files.

  Text format (sprites.txt):
      sprite Crab            <- name (becomes the label SprCrab)
      ..9....9..             <- one char per pixel:
      ...9999...                '.' = transparent (index 0)
      ..99A99A9.                '0'-'9', 'A'-'F' = palette index
      ...                       (0 is also transparent inside a sprite)
                             <- blank line or next `sprite` ends it

  PNG: python3 sprite2asm.py -o sprites.asm hero.png ...
       Each pixel is mapped to the nearest palette color; alpha < 128 or the
       nearest color being index 0 makes it transparent. Label = Spr + file name.

Output: sprites.asm with .def'd labels in .sect ".const":
      SprCrab   .byte   10, 6         ; width, height
                .byte   0x00, 0x90, ...
  or, with -o name.c, C: name.c with `const uint8_t SprCrab[] = { 10, 6, ... };`
  and name.h with the extern declarations (for C programs using tft4.h).
"""
import argparse, os, re, sys

# tft4 default palette (RGB888) - keep in sync with DefaultPalette in tft4.asm
PALETTE = [0x000000, 0x1D2B53, 0x7E2553, 0x008751, 0xAB5236, 0x5F574F, 0xC2C3C7, 0xFFF1E8,
           0xFF004D, 0xFFA300, 0xFFEC27, 0x00E436, 0x29ADFF, 0x83769C, 0xFF77A8, 0xFFCCAA]


def parse_text(path):
    sprites, name, rows = [], None, []
    def flush():
        if name and rows:
            sprites.append((name, rows[:]))
    for ln, raw in enumerate(open(path), 1):
        line = raw.rstrip('\n').rstrip()
        if not line.strip():
            flush(); name, rows = None, []
            continue
        if line.lstrip().startswith((';', '#')):
            continue
        m = re.match(r'\s*sprite\s+(\w+)\s*$', line)
        if m:
            flush(); name, rows = m.group(1), []
            continue
        if name is None:
            sys.exit(f"{path}:{ln}: pixels outside a `sprite NAME` block")
        px = []
        for ch in line.strip():
            if ch == '.':
                px.append(0)
            elif ch.upper() in '0123456789ABCDEF':
                px.append(int(ch, 16))
            else:
                sys.exit(f"{path}:{ln}: bad pixel character {ch!r}")
        if rows and len(px) != len(rows[0]):
            sys.exit(f"{path}:{ln}: row width {len(px)} != {len(rows[0])}")
        rows.append(px)
    flush()
    return sprites


def nearest(rgb):
    r, g, b = rgb
    best = min(range(16), key=lambda i: (((PALETTE[i] >> 16) - r) ** 2 +
                                         (((PALETTE[i] >> 8) & 255) - g) ** 2 +
                                         ((PALETTE[i] & 255) - b) ** 2))
    return best


def parse_png(path):
    from PIL import Image
    im = Image.open(path).convert('RGBA')
    w, h = im.size
    rows = []
    for y in range(h):
        row = []
        for x in range(w):
            r, g, b, a = im.getpixel((x, y))
            row.append(0 if a < 128 else nearest((r, g, b)))
        rows.append(row)
    name = re.sub(r'\W', '_', os.path.splitext(os.path.basename(path))[0])
    return [(name[:1].upper() + name[1:], rows)]


def emit(sprites, src_names):
    out = [";******************************************************************************",
           "; sprites.asm - generated by tools/sprite2asm.py from " + ", ".join(src_names),
           "; Do not edit by hand: change the art and run the tool again.",
           ";",
           "; Format: .byte width, height, then rows with 2 pixels per byte (left pixel",
           "; in the high nibble), each row padded to a whole byte. Index 0 = transparent.",
           ";******************************************************************************",
           "",
           "\t.def    " + ", ".join("Spr" + n for n, _ in sprites),
           "",
           "\t.sect   \".const\"",
           ""]
    total = 0
    for name, rows in sprites:
        w, h = len(rows[0]), len(rows)
        if w > 255 or h > 255:
            sys.exit(f"{name}: sprites are limited to 255x255")
        label = "Spr" + name
        out.append(f"{label:<15s} .byte   {w}, {h}{'':<20s}; {w}x{h}")
        for r in rows:
            rr = r + [0] * (w % 2)
            data = [(rr[i] << 4) | rr[i + 1] for i in range(0, len(rr), 2)]
            art = ''.join('.' if v == 0 else '%X' % v for v in r)
            out.append(f"{'':<15s} .byte   " + ", ".join(f"0x{b:02X}" for b in data) + f"    ; {art}")
            total += len(data)
        total += 2
        out.append("")
    out.append(f"; {len(sprites)} sprites, {total} bytes")
    out.append("\t.end")
    return "\n".join(out) + "\n"


def emit_c(sprites, src_names, header):
    out = ["/* generated by tools/sprite2asm.py from " + ", ".join(src_names) + " - do not edit.",
           " * tft4 sprites: width, height, rows (2 pixels per byte, left pixel in the high",
           " * nibble, rows padded to whole bytes). Index 0 = transparent. */",
           f'#include "{header}"', ""]
    for name, rows in sprites:
        w, h = len(rows[0]), len(rows)
        if w > 255 or h > 255:
            sys.exit(f"{name}: sprites are limited to 255x255")
        out.append(f"const uint8_t Spr{name}[{2 + h * ((w + 1) // 2)}] = {{ {w}, {h},")
        for r in rows:
            rr = r + [0] * (w % 2)
            data = [(rr[i] << 4) | rr[i + 1] for i in range(0, len(rr), 2)]
            art = ''.join('.' if v == 0 else '%X' % v for v in r)
            out.append("    " + ", ".join(f"0x{b:02X}" for b in data) + f",   /* {art} */")
        out.append("};")
    guard = re.sub(r'\W', '_', header).upper()
    h = [f"/* {header} - generated by tools/sprite2asm.py - do not edit. */",
         f"#ifndef {guard}", f"#define {guard}", "#include <stdint.h>", ""]
    h += [f"extern const uint8_t Spr{n}[{2 + len(r) * ((len(r[0]) + 1) // 2)}];   /* {len(r[0])}x{len(r)} */"
          for n, r in sprites]
    h += ["", "#endif", ""]
    return "\n".join(out) + "\n", "\n".join(h)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('inputs', nargs='+', help='sprites.txt and/or .png files')
    ap.add_argument('-o', '--output', default='sprites.asm')
    a = ap.parse_args()
    sprites = []
    for p in a.inputs:
        sprites += parse_png(p) if p.lower().endswith('.png') else parse_text(p)
    names = [n for n, _ in sprites]
    dup = {n for n in names if names.count(n) > 1}
    if dup:
        sys.exit(f"duplicate sprite names: {sorted(dup)}")
    srcs = [os.path.basename(p) for p in a.inputs]
    if a.output.endswith('.c'):
        hdr = a.output[:-2] + '.h'
        c, h = emit_c(sprites, srcs, os.path.basename(hdr))
        open(a.output, 'w').write(c)
        open(hdr, 'w').write(h)
    else:
        open(a.output, 'w').write(emit(sprites, srcs))
    print(f"{a.output}: {len(sprites)} sprites")


if __name__ == '__main__':
    main()
